CREATE TABLE [dbo].[T003_Asset_List] (
    [Group]                    NVARCHAR (255) NULL,
    [Name]                     NVARCHAR (255) NULL,
    [Description]              NVARCHAR (255) NULL,
    [Location]                 NVARCHAR (255) NULL,
    [IP Address]               NVARCHAR (255) NULL,
    [Manufacturer]             NVARCHAR (255) NULL,
    [Type]                     NVARCHAR (255) NULL,
    [Purchase Date]            NVARCHAR (255) NULL,
    [Serial]                   NVARCHAR (255) NULL,
    [Agent settings version]   NVARCHAR (255) NULL,
    [Disabled]                 NVARCHAR (255) NULL,
    [Account]                  NVARCHAR (255) NULL,
    [Source]                   NVARCHAR (255) NULL,
    [Activity Log]             NVARCHAR (255) NULL,
    [Approved Patches]         NVARCHAR (255) NULL,
    [Asset Custom Date 1]      NVARCHAR (255) NULL,
    [Asset Custom Date 2]      NVARCHAR (255) NULL,
    [Asset Custom Int 1]       NVARCHAR (255) NULL,
    [Asset Custom Int 2]       NVARCHAR (255) NULL,
    [Asset Custom List 1]      NVARCHAR (255) NULL,
    [Asset Custom List 2]      NVARCHAR (255) NULL,
    [Asset Custom Notes]       NVARCHAR (255) NULL,
    [Asset Custom Text 1]      NVARCHAR (255) NULL,
    [Asset Custom Text 2]      NVARCHAR (255) NULL,
    [Asset ID]                 NVARCHAR (255) NULL,
    [BIOS Type]                NVARCHAR (255) NULL,
    [Building]                 NVARCHAR (255) NULL,
    [Bytes in]                 NVARCHAR (255) NULL,
    [Bytes out]                NVARCHAR (255) NULL,
    [CPU Count]                NVARCHAR (255) NULL,
    [CPU Model]                NVARCHAR (255) NULL,
    [CPU Speed]                NVARCHAR (255) NULL,
    [Catalog number]           NVARCHAR (255) NULL,
    [CPU Vendor]               NVARCHAR (255) NULL,
    [Change SR Patches]        NVARCHAR (255) NULL,
    [Company]                  NVARCHAR (255) NULL,
    [Company Serial]           NVARCHAR (255) NULL,
    [Cubic]                    NVARCHAR (255) NULL,
    [Current Carrier]          NVARCHAR (255) NULL,
    [Denied Patches]           NVARCHAR (255) NULL,
    [Department]               NVARCHAR (255) NULL,
    [Display Adapter]          NVARCHAR (255) NULL,
    [Display Memory]           NVARCHAR (255) NULL,
    [Display Resolution]       NVARCHAR (255) NULL,
    [External Serial]          NVARCHAR (255) NULL,
    [Failed Patches]           NVARCHAR (255) NULL,
    [Floor]                    NVARCHAR (255) NULL,
    [Free Memory Banks]        NVARCHAR (255) NULL,
    [Free Space]               NVARCHAR (255) NULL,
    [Home Carrier]             NVARCHAR (255) NULL,
    [ICC]                      NVARCHAR (255) NULL,
    [IMEI]                     NVARCHAR (255) NULL,
    [Installed Patches]        NVARCHAR (255) NULL,
    [Last Access Time]         NVARCHAR (255) NULL,
    [Last Boot]                NVARCHAR (255) NULL,
    [Last Maintenance]         NVARCHAR (255) NULL,
    [Last Patch]               NVARCHAR (255) NULL,
    [Last Scan]                NVARCHAR (255) NULL,
    [Links to other Items]     NVARCHAR (255) NULL,
    [MAC Address]              NVARCHAR (255) NULL,
    [MDM Policy]               NVARCHAR (255) NULL,
    [Memory]                   NVARCHAR (255) NULL,
    [Missing Patches]          NVARCHAR (255) NULL,
    [Missing Patches List]     NVARCHAR (255) NULL,
    [Model]                    NVARCHAR (255) NULL,
    [Monitor]                  NVARCHAR (255) NULL,
    [Monitor Serial]           NVARCHAR (255) NULL,
    [OS Name]                  NVARCHAR (255) NULL,
    [Occupied Memory Banks]    NVARCHAR (255) NULL,
    [OS Serial]                NVARCHAR (255) NULL,
    [Operating System Type]    NVARCHAR (255) NULL,
    [Operating System Version] NVARCHAR (255) NULL,
    [Owner]                    NVARCHAR (255) NULL,
    [Ownership]                NVARCHAR (255) NULL,
    [Parent Asset]             NVARCHAR (255) NULL,
    [Patch Management]         NVARCHAR (255) NULL,
    [Patch Management Policy]  NVARCHAR (255) NULL,
    [Pending Patches]          NVARCHAR (255) NULL,
    [Phone Number]             NVARCHAR (255) NULL,
    [Purchase Cost]            NVARCHAR (255) NULL,
    [RDS]                      NVARCHAR (255) NULL,
    [Service Pack]             NVARCHAR (255) NULL,
    [Snmp Custom Text 1]       NVARCHAR (255) NULL,
    [Snmp Custom Text 10]      NVARCHAR (255) NULL,
    [Snmp Custom Text 11]      NVARCHAR (255) NULL,
    [Snmp Custom Text 12]      NVARCHAR (255) NULL,
    [Snmp Custom Text 13]      NVARCHAR (255) NULL,
    [Snmp Custom Text 14]      NVARCHAR (255) NULL,
    [Snmp Custom Text 15]      NVARCHAR (255) NULL,
    [Snmp Custom Text 16]      NVARCHAR (255) NULL,
    [Snmp Custom Text 17]      NVARCHAR (255) NULL,
    [Snmp Custom Text 18]      NVARCHAR (255) NULL,
    [Snmp Custom Text 19]      NVARCHAR (255) NULL,
    [Snmp Custom Text 2]       NVARCHAR (255) NULL,
    [Snmp Custom Text 20]      NVARCHAR (255) NULL,
    [Snmp Custom Text 3]       NVARCHAR (255) NULL,
    [Snmp Custom Text 4]       NVARCHAR (255) NULL,
    [Snmp Custom Text 5]       NVARCHAR (255) NULL,
    [Snmp Custom Text 6]       NVARCHAR (255) NULL,
    [Snmp Custom Text 7]       NVARCHAR (255) NULL,
    [Snmp Custom Text 8]       NVARCHAR (255) NULL,
    [Snmp Custom Text 9]       NVARCHAR (255) NULL,
    [Snmp Params]              NVARCHAR (255) NULL,
    [Software]                 NVARCHAR (MAX) NULL,
    [Status]                   NVARCHAR (255) NULL,
    [Storage Capacity]         NVARCHAR (255) NULL,
    [Storage Devices]          NVARCHAR (255) NULL,
    [Supplier]                 NVARCHAR (255) NULL,
    [Support provider]         NVARCHAR (255) NULL,
    [SysAid agent version]     NVARCHAR (255) NULL,
    [Total Memory Banks]       NVARCHAR (255) NULL,
    [Update Time]              NVARCHAR (255) NULL,
    [Users]                    NVARCHAR (255) NULL,
    [Version]                  NVARCHAR (255) NULL,
    [ID]                       INT            NOT NULL,
    [Warranty Expiration]      NVARCHAR (255) NULL
);

